[phases.setup]
aptPkgs = [
    "build-essential",
    "cmake",
    "libboost-all-dev",
    "libx11-6",
    "libgl1-mesa-glx",
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender-dev",
    "libgomp1",
    "libopenblas-dev",
    "liblapack-dev"
]

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:8080 --worker-class eventlet -w 1 server:app"
