[phases.setup]
aptPkgs = [
    "cmake",
    "libboost-all-dev",
    "libgl1",             ‚Üê FIXED!
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender-dev",
    "libgomp1",
    "libx11-6",
    "libxcb1"
]
